version: '3.6'
services:
  # express web services:
  web1:
    build: .
    ports:
      - 3000
  web2:
    build: .
    ports:
      - 3000
  web3:
    build: .
    ports:
      - 3000
  # nginx load balancer:
  load-balancer:
    build: nginx/
    ports:
      - 80:80
    links:
      - web1
      - web2
      - web3
    volumes:
      # allows you to run docker commands inside container:
      - /var/run/docker.sock:/var/run/docker.sock
